### ISSUE TITLE
Timer don't seem to update correctly

### ISSUE THREAD

**Issue by asteman** [jeroenbos22/homey.countdown#17]
I have flows in two rooms that upon movement, changes color/brightness of that room and starts/updates a timer for x seconds. On many occasions it seems like the timer never resets to x seconds upon consecutive movement in that room. When the timer expires, another flow restores the light despite we are in that room triggering one of the two sensors.

Maybe I'm doing it wrong or this might not be a countdown timer issue rather than an Homey one.

I've tried both one trigger flow per sensor and using the device motion and filter on the zone. Same behavior in both scenarios.

Trigger
![image](https://user-images.githubusercontent.com/25367091/51568053-1c970680-1e99-11e9-82f6-da1c1597d1f3.png)

Restore
![image](https://user-images.githubusercontent.com/25367091/51568108-3b959880-1e99-11e9-9693-1a6eb5078c70.png)

How can I continue testing?

Homey 1.5.13
Countdown timer 1.2.3

edit:
Another view of the issue. The two shades of green are my two PIRs. The line is my RGB strip changeing color. Timer is 5 minutes. The 4 rings indicate situations the timer should not have expired.
![image](https://user-images.githubusercontent.com/25367091/51628556-9389d900-1f45-11e9-9073-500bda04fdaa.png)

**Comment by jeroenbos22** [comment]
Seems like you are using a Fibaro motion, is this the zwave plus version? Its a known Homey core issue this motion sensor not always detecting motion because it is hanging (either on or off). Think this might be the cause of you're problem here.

**Comment by asteman** [comment]
Thanks for reply, @jeroenbos22 . Sensors are not the plus version. In one room there are 2 Fibaro non-plus sensors and in the other room it's 1 Fibaro non-plus and one Aeotec multisensor 6. Both rooms display the same behavior as described above. 

Also, these sensors has been running without any issue for over 3 years in my Vera setup. Using same sensors and same type of logic (Used PLEG in the Vera system).

I'm sorry these facts wasn't included in my first post.
