### ISSUE TITLE
'stop a timer' with timer name equals a variable

### ISSUE THREAD

**Issue by lied** [jeroenbos22/homey.countdown#22]
I want to do the following:
(issue in the forum: https://community.athom.com/t/fresh-air-close-window-reminder/9110/14)

1. Flow: Contact Alarm goes off; then: create timer with the device name as timer name
2. Flow: a Contact Alarm alarm turned off; then: stop timer with the device name
3. Flow: timer finished; then: send notification with “door/window still open…”

Unfortunately it's not possible to use the "device name" variable in the 'stop a timer' action. Could this be implemented easily?

**Comment by Milanzor** [comment]
If your contact alarms trigger cards support tags that contain the device name, you should simply be able to start a timer with that tag as its name and set a variable with "tag" as name to true. My KlikAanKlikUit door sensor does not have device name tags though.

*For now, your only solution is manually doing this for all windows you have*
- Trigger: Contact alarm "Window bedroom" turns on => Start a timer with name "Window bedroom" and set variable "Window bedroom open " to true
- Trigger: Contact alarm "Window bedroom" turns off => Stop the timer with name "Window bedroom" and set variable "Window bedroom open" to false
- Trigger: Timer "Window bedroom" runs out AND variable "Window bedroom open" === true => Send notification

Don't forget that you don't get new windows very often, so it's a matter of setting it up once plus if you set it up your way, all your windows will have the same amount of time, while larger rooms might take longer to fill up.

**Comment by lied** [comment]
@Milanzor I have the variable "Device Name" available in the When-Part of the Flow. Unfortunately, I cannot use this variable in the "stop a timer" card. The "stop a timer" card forces me to select an existing timer, and I cannot use a Tag here.
I really would appreciate this enhancement, as I have 15 window sensors to configure. ;-)
