### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by FrankRinkens** [jeroenbos22/homey.countdown#28]
Hi thanks for this app!!, I have a feature request:

- rename a timer
- pauze a timer

best regards

**Comment by Milanzor** [comment]
Today we'll provide a beta update of this app to Athom, the update will add the following Actions:

- Pause
- Resume
- Pause/Resume

I don't think we'll provide a way to rename a timer, you'll have to do that manually.

**Comment by jeroenbos22** [comment]
Try the new test-version of the app on https://homey.app/nl-nl/app/homey.countdown/Countdown-timers/test/

This should fix your issue!
