### ISSUE TITLE
Stop timer fire finished flow

### ISSUE THREAD

**Issue by JirLap** [jeroenbos22/homey.countdown#29]
I suppose it is not a good idea fire "Timer finished" after stopping by "Stop timer" action.
Possibly it is because set to 0=countdown (it should by better set it to -1).

**Comment by Krisstenswe** [comment]
Great app, BUT I have the same problem. I have to use "Stop all timers" instead of "Stop a timer" to make it work...

**Comment by Milanzor** [comment]
Yeah, the `Stop timer` action does indeed fire the 'Timer finished' because of that reason. In the upcoming beta release, actions `Pause, Resume and Pause/Resume` are added, perhaps that will help your problem.

**Comment by jeroenbos22** [comment]
Try the new test-version of the app on https://homey.app/nl-nl/app/homey.countdown/Countdown-timers/test/

This should fix your issue!

**Comment by Krisstenswe** [comment]
Thanks!

I have run some tests and it’s working great!

 

Kind regards,

/Kristofer 

 

Från: Jeroen [mailto:notifications@github.com] 
Skickat: den 14 november 2019 19:57
Till: NotQuiteZen/homey.countdown <homey.countdown@noreply.github.com>
Kopia: Krisstenswe <kristofer@stenum.se>; Comment <comment@noreply.github.com>
Ämne: Re: [NotQuiteZen/homey.countdown] Stop timer fire finished flow (#29)

 

Try the new test-version of the app on https://homey.app/nl-nl/app/homey.countdown/Countdown-timers/test/

This should fix your issue!
