### ISSUE TITLE
No function with Homey 2.0.0

### ISSUE THREAD

**Issue by tobpet** [jeroenbos22/homey.countdown#3]
After update to 2.0.0 timer is not functional.

**Comment by jeroenbos22** [comment]
This countdown app was especially made for v2. The previous countdown app does not work on v2. You need the app with the image of the pink timer.

Greetings Jeroen

**Comment by tobpet** [comment]
I have that one. But timer seems not to trigger...

**Comment by jeroenbos22** [comment]
You first need to set a timer using the actioncard. If a timer starts / finishes it triggers the trigger-cards.

The apps are not compatible. The previous app is not even mine. If you had timers with the other app you need to reconfigure the flows you use timers in.

Jeroen

**Comment by tobpet** [comment]
Thats how I use it.
Card under then, set name of timer and seconds to run. 
Under other flow, when that timer stops...

But no action is done...

**Comment by jeroenbos22** [comment]
Then the names of the timers don’t match. V2 has a known bug for sometimes leaving out some characters that you filled in. For example if you save a flow with the name test it could save it as tes.

That will be fixed soon in homey core. And we are working on an autocomplete so there can’t be any mismatch in the future.

If the problem persists try to remove the power for 2 minutes and then plug homey back in. Maybe some other v2 bug is bugging you’re homey atm.

Jeroen

**Comment by irritanterik** [comment]
Other app is upgraded to SDK 2.0 now https://github.com/ralfvd/nl.bevlogenheid.countdown/commit/398a6b8b8d4b0a427efc0c18784db450e956a082
