### ISSUE TITLE
Resume countdown.

### ISSUE THREAD

**Issue by groetsels** [jeroenbos22/homey.countdown#34]
Is it possible to make a change that after Homey has restartet (reboot) the counters will continue counting down?

**Comment by Milanzor** [comment]
I'm not sure if that's viable, when Homey reboots, every app and the memory is cleared. There is no persistent component to store the timers in, except for file storage. I think that storing timers and their remaining time on disk is probably not very stable and not how Homey intends apps to use it's resources.

If someone comes up with a way this would be possible, I'd be happy to look further into it!
